create table `t_balance` (
    `序号` int unsigned not null auto_increment,
    `TS 股票代码` varchar(100) not null default '',
    `名称` varchar(100) not null default '',
    `行业名称` varchar(100) not null default '',
    `公告日期` varchar(200) not null default '',
    `报告日期` varchar(200) not null default '',
    `总资产` float not null default 0,
    `总资产同比` float not null default 0,
    `固定资产` float not null default 0,
    `货币资金` float not null default 0,
    `货币资金同比` float not null default 0,
    `应收账款` float not null default 0,
    `应收账款同比` float not null default 0,
    `存货` float not null default 0,
    `存货同比` float not null default 0,
    `总负债` float not null default 0,
    `总负债同比` float not null default 0,
    `应付账款` float not null default 0,
    `应付账款同比` float not null default 0,
    `预收账款` float not null default 0,
    `预收账款同比` float not null default 0,
    `股东权益合计` float not null default 0,
    `股东权益同比` float not null default 0,
    `流动比率` float not null default 0,
    `资产负债率` float not null default 0,
    primary key(`序号`),
    unique key `idx_date` (`报告日期`)
)engine=InnoDB auto_increment=1 default charset=utf8mb4;