create table `t_cashflow` (
    `序号` int unsigned not null auto_increment,
    `TS 股票代码` varchar(100) not null default '',
    `名称` varchar(100) not null default '',
    `行业名称` varchar(100) not null default '',
    `公告日期` varchar(100) not null default '',
    `报告日期` varchar(200) not null default '',
    `净现金流` float not null default 0,
    `净现金流同比` float not null default 0,
    `经营性现金流量净额` float not null default 0,
    `经营性现金流量净额占比` float not null default 0,
    `销售商品、提供劳务收到的现金金额` float not null default 0,
    `销售商品、提供劳务收到的现金占比` float not null default 0,
    `支付员工现金金额` float not null default 0,
    `支付员工现金占比` float not null default 0,
    `投资性现金流量净额` float not null default 0,
    `投资性现金流量净额占比` float not null default 0,
    `取得投资收益收到的现金金额` float not null default 0,
    `取得投资收益收到的现金占比` float not null default 0,
    `构建固定资产、无形资产和其他长期资产支付的现金金额` float not null default 0,
    `构建固定资产、无形资产和其他长期资产支付的现金占比` float not null default 0,
    `融资性现金流量净额` float not null default 0,
    `融资性现金流量净额占比` float not null default 0,
    primary key(`序号`),
    unique key `idx_date` (`报告日期`)
)engine=InnoDB auto_increment=1 default charset=utf8mb4;
