create table `t_income` (
    `序号` int unsigned not null auto_increment,
    `TS 股票代码` varchar(100) not null default '',
    `名称` varchar(100) not null default '',
    `行业名称` varchar(100) not null default '',
    `公告日期` varchar(100) not null default '',
    `报告日期` varchar(200) not null default '',
    `净利润` float not null default 0,
    `净利润同比` float not null default 0,
    `扣非归母净利润` float not null default 0,
    `扣非归母净利润同比` float not null default 0,
    `营业总收入` float not null default 0,
    `营业总收入同比` float not null default 0,
    `营业支出` float not null default 0,
    `营业支出同比` float not null default 0,
    `销售费用` float not null default 0,
    `管理费用` float not null default 0,
    `财务费用` float not null default 0,
    `营业总支出` float not null default 0,
    `营业总支出同比` float not null default 0,
    `营业利润` float not null default 0,
    `营业利润同比` float not null default 0,
    `利润总额` float not null default 0,
    `营业税` float not null default 0,
    `营业税增长` float not null default 0,
    primary key(`序号`),
    unique key `idx_date` (`报告日期`)
)engine=InnoDB auto_increment=1 default charset=utf8mb4;